### ISSUE TITLE
添加集成提示无效登陆？

### ISSUE THREAD

**Issue by Lancenas** [daxingplay/home-assistant-vaillant-plus#13]
使用的是1.2.0版本
![iShot_2023-12-19_10 26 45](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/32763979/cc30c6c0-99cc-4fa9-ae1e-0aaa2d194037)

**Comment by daxingplay** [comment]
手机 App 能正常登录吗？
Home Assistant 的集成里把这个集成的调试日志打开，贴一下详细日志？

**Comment by Lancenas** [comment]
> 手机 App 能正常登录吗？ Home Assistant 的集成里把这个集成的调试日志打开，贴一下详细日志？

手机客户端是“威能家”，能正常登陆。
此错误来自自定义集成。

Logger: custom_components.vaillant_plus.config_flow
Source: custom_components/vaillant_plus/config_flow.py:65
Integration: Vaillant Plus (documentation, issues)
First occurred: 10:27:03 (1 occurrences)
Last logged: 10:27:03

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/vaillant_plus_cn_api/api.py", line 91, in _request
    async with session.request(method, f"{API_HOST}/{url}", **kwargs) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host vicapi.vaillant.com.cn:443 ssl:default [Try again]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/vaillant_plus/config_flow.py", line 65, in async_step_user
    user_info = await client.login(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vaillant_plus_cn_api/api.py", line 125, in login
    resp = await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vaillant_plus_cn_api/api.py", line 101, in _request
    raise RequestError(f"Error requesting data from {url}: {err}") from err
vaillant_plus_cn_api.errors.RequestError: Error requesting data from auth/oauth/token?grant_type=password: Cannot connect to host vicapi.vaillant.com.cn:443 ssl:default [Try again]

**Comment by daxingplay** [comment]
看起来你 HA 这个机器上访问不了 vicapi.vaillant.com.cn 这个域名。你 ping 一下这个域名看看呢？

**Comment by Lancenas** [comment]
> 看起来你 HA 这个机器上访问不了 vicapi.vaillant.com.cn 这个域名。你 ping 一下这个域名看看呢？
已经在hosts添加了 47.101.34.198  vicapi.vaillant.com.cn
![iShot_2023-12-20_12 34 51](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/32763979/6f95f9a9-b7d9-4e52-a15e-23ca7b37aadb)

**Comment by daxingplay** [comment]
看下你的机器上是否启用了 IPv6，如果启用了的话，并且并不能真正访问 IPv6 的网站（和上面这个域名没关系，但是说明 IPv6 的网络是有问题的），一般就会出现这个问题。
有两种方式禁用掉：
1. Home Assistant 系统设置里关闭。参考这个文档：https://www.nabucasa.com/config/troubleshooting/unable_to_reach_the_home_assistant_cloud/#:~:text=If%20there%20is%20an%20IPv6,option%20and%20save%20the%20changes.
2. 如果上面的设置找不到的话，可以直接系统里禁用。`sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1`。如果没问题的话，可以把这个设置写入到 `sysctl.conf` 里。

你试一试是否能解决这个问题呢？

**Comment by Lancenas** [comment]
> 看下你的机器上是否启用了 IPv6，如果启用了的话，并且并不能真正访问 IPv6 的网站（和上面这个域名没关系，但是说明 IPv6 的网络是有问题的），一般就会出现这个问题。 有两种方式禁用掉：
> 
> 1. Home Assistant 系统设置里关闭。参考这个文档：https://www.nabucasa.com/config/troubleshooting/unable_to_reach_the_home_assistant_cloud/#:~:text=If%20there%20is%20an%20IPv6,option%20and%20save%20the%20changes.
> 2. 如果上面的设置找不到的话，可以直接系统里禁用。`sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1`。如果没问题的话，可以把这个设置写入到 `sysctl.conf` 里。
> 
> 你试一试是否能解决这个问题呢？

还是无法登陆。你能正常集成吗？

**Comment by daxingplay** [comment]
你是用哪种方式关闭 IPv6 的？我能正常使用。我也是遇到过你这种情况，我用第二种方式关闭 IPv6 之后就正常了。

**Comment by Lancenas** [comment]
> 你是用哪种方式关闭 IPv6 的？我能正常使用。我也是遇到过你这种情况，我用第二种方式关闭 IPv6 之后就正常了。

还是不行。用户名是手机号？

**Comment by daxingplay** [comment]
> 还是不行。用户名是手机号？

对，是手机号。你看日志的话失败的原因是啥？如果还是和之前一样是这个错误：`Cannot connect to host vicapi.vaillant.com.cn:443 ssl:default [Try again]`，那应该还是网络因素。

**Comment by daxingplay** [comment]
你 HomeAssistant 是什么版本啊？

**Comment by Lancenas** [comment]
> 你 HomeAssistant 是什么版本啊？

我PVE安装的是Home Assistant OS 11.2，Vaillant服务器一直无法登陆。
![iShot_2023-12-29_12 37 38](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/32763979/64097911-8d18-45cb-87e9-bdf7edcf1610)

**Comment by czg82324** [comment]
我也是同样的问题，用的最新的1.2.2版本，关闭ipv6没有用，homeassistant是docker上的最新版本，我是装在群晖里的

**Comment by daxingplay** [comment]
我看了下，因为用的 HA 自带的一个请求库，用了这个请求库的应该都有类似问题。后面我计划换一个，但代码和测试用例很多要重写了，需要花点时间😓

**Comment by czg82324** [comment]
大佬啥时候修复这个问题啊？

**Comment by daxingplay** [comment]
> 大佬啥时候修复这个问题啊？

尽快吧

**Comment by daxingplay** [comment]
> 大佬啥时候修复这个问题啊？

你用的是哪个版本的 HA？

**Comment by czg82324** [comment]
发自我的手机-------- 原始邮件 --------发件人： 橘子 ***@***.***>日期： 2024年4月3日周三 21:22收件人： daxingplay/home-assistant-vaillant-plus ***@***.***>抄送： czg82324 ***@***.***>, Comment ***@***.***>主    题： Re: [daxingplay/home-assistant-vaillant-plus] 添加集成提示无效登陆？ (Issue #13)

大佬啥时候修复这个问题啊？

你用的是哪个版本的 HA？

**Comment by czg82324** [comment]
2024.3.1的os版本发自我的手机-------- 原始邮件 --------发件人： 橘子 ***@***.***>日期： 2024年4月3日周三 21:22收件人： daxingplay/home-assistant-vaillant-plus ***@***.***>抄送： czg82324 ***@***.***>, Comment ***@***.***>主    题： Re: [daxingplay/home-assistant-vaillant-plus] 添加集成提示无效登陆？ (Issue #13)

大佬啥时候修复这个问题啊？

你用的是哪个版本的 HA？

**Comment by daxingplay** [comment]
各位大佬试一试 v1.2.4 这个版本。
