### ISSUE TITLE
MiGo Support?

### ISSUE THREAD

**Issue by FabioEight** [daxingplay/home-assistant-vaillant-plus#4]
Hello,
Does this component supports MiGo platform as well?
MiGo is a rebrand of the same Vaillant platform, currently supported by this addon:
https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/

Thank you!

**Comment by daxingplay** [comment]
Which country are you using Vaillant?

**Comment by FabioEight** [comment]
> Which country are you using Vaillant?

Hello, I’m using it from Italy

**Comment by daxingplay** [comment]
Sorry, after some digging, I found that the APIs Vaillant used is totally different from those used in mainland China. So this integration will only support Vaillant vSmart devices sold in mainland China.
